### ISSUE TITLE
sensor doesn't show up in sensor list/header problem

### ISSUE THREAD

**Issue by kleeaar** [kit-ipe/bora#16]
1) I just wanted to add a new sensor (320-RTY-3-4103, 320-RTY-3-5102) to the sensorlist via adei2rest.
The _/add/..._ page returned _{"success": "Data entry inserted."}_ but in the designer the sensor doesn't show up in the sensor list of the designer.
Maybe this is because of the new login?
If I try to add it again, it says _{"Error": "Variable already available in varname file."}_, so the add-function seems to work fine.
2) Could you add a function that removes special characters of the element id of the header elements? If one e.g. wants to add a *, :, + in the header, the id of the element will be not formatted correctly, and the css/JS can't access it (therefore positioning etc in the designer doesnt work). Using Hex or Unicode doesn't solve the problem, because they are both having special characters like + and & or # in their names. 
That would be great!

**Comment by nicolaisi** [comment]
That is an ugly bug. I'm working on it now.

**Comment by nicolaisi** [comment]
So, I'd fixed point 1 and point 2. 

Please not that I cannot handle umlaut or esset (maybe I'll think about this later if it's really required). The header now accepts alphanumerical values.

Besides the fixes, I'd 'improved' the user interaction. Before this, if you make changes to the existing data item, you need to remove the old item and re-add again. This is no longer the case, if you working on a data item and added an "equation", press save and refresh your status screen.

Also, there's no longer the highlight button, as Andreas pointed out that it was redundant. As soon as you choose any sensor, it be automatically be highlighted.

I welcome more feedback. Thanks for your feedback so far, it has been useful to drive this forward.

By the way, if you're wondering why some of your new changes went missing. It was because I made a big mistake and erased everything 👎  I took the backup files to restore the state 👍 

d15db9ab3bfd1a00ecaf3a0aaaeee477c99b526a

**Comment by kleeaar** [comment]
Great!
I think we won't need umlauts, so that's fine!
I already recognized the enhancements, which really improved the interface! :+1: 
We didn't change a lot since the last backup, so this was no problem for us ;-)

**Comment by nicolaisi** [comment]
One more stuff, the math feature I implemented is from this:
http://mathjs.org/

which means, whatever math functions available there can be used. As far as I'd read the documentation, they cover a broad range of math functions.
