### ISSUE TITLE
Unable to uncheck linkhtml

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/bora#33]
For example, comm_fronius once checked, is not able to uncheck it. I guess it's something with the designer page.

**Comment by chanhoonseng** [comment]
Hi,

I think i know where the problem is. Everytime u made changes to commbit,
alarm, valve and integer-to-string, inide the value field, you need to
rewrite the dictionary in the form {"key1":"value1","key2":"value2"}, so
that the changes you made can be saved. This is a little bug which i plan
to solve it when i come next time. So for the time being we have tp rewrite
the dictionary format.

Sorry for the inconvenience.
Hanson

On 17 Jan 2017 14:23, "Nicholas Tan Jerome" <notifications@github.com>
wrote:

For example, comm_fronius once checked, is not able to uncheck it. I guess
it's something with the designer page.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kit-ipe/bora/issues/33>, or mute the thread

**Comment by nicolaisi** [comment]
It's fine, not an urgent bug. We can wait till you are slightly more free. I just want to keep track of these bugs.
